### ISSUE TITLE
A question about compute gain

### ISSUE THREAD

**Issue by vincent341** [ElisevanderPol/symmetrizer#1]
Hi. Would you mind letting me know what  "[gain](https://github.com/ElisevanderPol/symmetrizer/blob/8dae02bee2ba7132ae4fb07e07020767d280842c/symmetrizer/nn/modules.py#L81)" is? Why compute gain? Thanks very much.

**Comment by ElisevanderPol** [comment]
Hi, gain is a standard parameter used for initialization, see for more info [the Pytorch documentation](https://pytorch.org/docs/stable/nn.init.html).
